### PR TITLE
Sass and test file reorganization, Gulp updates, and ESLint installation.

### PR DESCRIPTION
**Pull request by hdavidzhu**
@zchi88

### CODE REVIEW

**Comment by sihrc** [comment]
LGTM -> rebase to just 
- [x] correct file locations
- [x] update gulp tasks
- [x] eslint styling

**Comment by hdavidzhu** [comment]
@sihrc WOAH how did you make those checkboxes? That is soooo sweet.

**Comment by sihrc** [comment]
It's markup ! `- [ ] text`

**Comment by sihrc** [comment]
:+1: go ahead and merge at will

**Pull request merged**
